create table if not exists public.post_reactions (
  id bigint generated by default as identity primary key,
  post_id text not null,
  type text not null check (type in ('❤️','🔥','👏','😂')),
  visitor_id text not null,
  created_at timestamptz not null default now()
);
create unique index if not exists one_reaction_per_visitor on public.post_reactions(post_id, type, visitor_id);
create index if not exists reactions_post_idx on public.post_reactions(post_id);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id text not null,
  name text not null check (char_length(name) between 1 and 60),
  body text not null check (char_length(body) between 1 and 1000),
  approved boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists comments_post_idx on public.comments(post_id, created_at desc);

alter table public.post_reactions enable row level security;
alter table public.comments enable row level security;

drop policy if exists "public read reactions" on public.post_reactions;
create policy "public read reactions" on public.post_reactions for select using (true);
drop policy if exists "public add reactions" on public.post_reactions;
create policy "public add reactions" on public.post_reactions for insert with check (char_length(visitor_id) >= 8);

drop policy if exists "public read approved comments" on public.comments;
create policy "public read approved comments" on public.comments for select using (approved = true);
drop policy if exists "public submit comments" on public.comments;
create policy "public submit comments" on public.comments for insert with check (approved = false and char_length(name) between 1 and 60 and char_length(body) between 1 and 1000);
